version: '3.7'

services:
  el01:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.14.1
    container_name: el01
    ulimits:
      memlock:
        soft: -1
        hard: -1
    ports:
      - 9200:9200
      - 9300:9300
    environment:
      - discovery.type=single-node
    networks:
      - elastic

  kib01:
    image: docker.elastic.co/kibana/kibana:7.14.1
    container_name: kib01
    ports:
      - 5601:5601
    environment:
      ELASTICSEARCH_URL: http://el01:9200
      ELASTICSEARCH_HOSTS: http://el01:9200
    networks:
      - elastic

networks:
  elastic:
    driver: bridge